// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjAhI0l3mdwQtz1PMC6ACI6nrmoV1M7qE',
    appId: '1:1057928266064:web:8e781d1341f57cedd56c55',
    messagingSenderId: '1057928266064',
    projectId: 'crypto-2c0cf',
    authDomain: 'crypto-2c0cf.firebaseapp.com',
    storageBucket: 'crypto-2c0cf.appspot.com',
    measurementId: 'G-TCPWXS38VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbUEhdR0ucpijuVnFmvE4nDYL_9zajo0M',
    appId: '1:1057928266064:android:b970be06ef7b6b9bd56c55',
    messagingSenderId: '1057928266064',
    projectId: 'crypto-2c0cf',
    storageBucket: 'crypto-2c0cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYG0vkxbrjpx9pizFeA3QGU2HRmOb_uLg',
    appId: '1:1057928266064:ios:5766ff5fd38cf2abd56c55',
    messagingSenderId: '1057928266064',
    projectId: 'crypto-2c0cf',
    storageBucket: 'crypto-2c0cf.appspot.com',
    androidClientId: '1057928266064-k0ndrmqe3jp4fdpatfh4020fd9bvttna.apps.googleusercontent.com',
    iosClientId: '1057928266064-qlvs47edjjbc08a98eo7lul5k7k0cr3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.honeyMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYG0vkxbrjpx9pizFeA3QGU2HRmOb_uLg',
    appId: '1:1057928266064:ios:4a9a18d07d53dd6fd56c55',
    messagingSenderId: '1057928266064',
    projectId: 'crypto-2c0cf',
    storageBucket: 'crypto-2c0cf.appspot.com',
    androidClientId: '1057928266064-k0ndrmqe3jp4fdpatfh4020fd9bvttna.apps.googleusercontent.com',
    iosClientId: '1057928266064-6s7hu4bv2e8se0mico1ei1cbpqqk0bgr.apps.googleusercontent.com',
    iosBundleId: 'com.example.honeyMobile.RunnerTests',
  );
}
