String EMAIL = 'email';
String MANUAL_LOGIN_ACCOUNT = 'MANUAL_LOGIN_ACCOUNT';
Map<String, String> OTP_USECASE = {
  MANUAL_LOGIN_ACCOUNT: MANUAL_LOGIN_ACCOUNT,
  REGISTER_ACCOUNT: REGISTER_ACCOUNT
};
String PHONE = 'phone';

String REGISTER_ACCOUNT = 'REGISTER_ACCOUNT';
Map<String, String> TYPE_OTP = {EMAIL: EMAIL, PHONE: PHONE};
